name: Deploy Infrastructure

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

defaults:
  run:
    working-directory: terraform

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_access_token: ${{ secrets.ACCESS_TOKEN }}

jobs:
  tf_deploy:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Initialize Terraform
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -input=false -out=tfplan

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan

    - name: Retrieve API Gateway Invoke URL
      run: |
        API_URL=$(terraform output -raw api_gateway_invoke_url)
        echo $API_URL
        echo "API_URL=${API_URL}" >> $GITHUB_ENV

    - name: Update index.html
      run: |
        sed -i "s|__INVOKE_URL__|${API_URL}|g" index.html
        cat index.html
      working-directory: src

    - name: Commit and Push Changes
      run: |
        git config --global user.email "hngiap94@gmail.com"
        git config --global user.name "hngiap94"
        git add index.html
        git commit -m "Update API Gateway URL in index.html"
        git push origin master
      working-directory: src